.PHONY: populate-descriptions populate_item_embeddings

populate-descriptions:
	uv run python -m scripts.populate_item_descriptions

populate-embeddings:
	uv run python -m scripts.populate_item_embeddings